name: CI
on: [push, pull_request]
jobs:
  deploy:
    environment: ${{ github.ref_name == 'main' && 'dev' || 'dev' }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: set up node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: install dependencies
        run: npm install

      - name: run lint
        run: npm run lint

      - name: run tests
        run: npm test

      - name: build
        run: npm run build
    
      - name: Test AWS access
        run: aws s3 ls
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-southeast-2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Deploy to S3
        run: aws s3 sync ./build s3://${{ secrets.AWS_S3_BUCKET }} --delete
