name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: set up node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: install dependencies
        run: npm install

      - name: run lint
        run: npm run lint

      - name: run tests
        run: npm test

      - name: build
        run: npm run build
    
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test AWS access
        run: aws s3 ls
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-southeast-2
      
      - name: Deploy to S3
        uses: aws-actions/configure-aws-credentials@v4
        with:
          args: --delete
          source: ./build
          destination: s3://${{ env.AWS_S3_BUCKET }}
        env:
          AWS_S3_BUCKET: s3://${{ env.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-southeast-2
